import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'movie_details_model.g.dart';

/// A data model representing the detailed information of a movie.
///
/// Annotated with [HiveType] for local storage and [JsonSerializable] for API communication.
@HiveType(typeId: 2)
@JsonSerializable(explicitToJson: true)
class MovieDetailsModel extends HiveObject {
  /// Indicates if the movie is intended for an adult audience.
  @HiveField(0)
  final bool? adult;

  /// The path to the movie's backdrop image.
  @HiveField(1)
  @JsonKey(name: 'backdrop_path')
  final String? backdropPath;

  /// Information about the collection the movie belongs to (if any).
  @HiveField(2)
  @JsonKey(name: 'belongs_to_collection')
  final dynamic belongsToCollection;

  /// The budget of the movie in dollars.
  @HiveField(3)
  final int? budget;

  /// A list of genres associated with the movie.
  @HiveField(4)
  final List<Genre>? genres;

  /// The URL of the movie's official homepage.
  @HiveField(5)
  final String? homepage;

  /// The unique identifier for the movie.
  @HiveField(6)
  final int? id;

  /// The IMDb identifier for the movie.
  @HiveField(7)
  @JsonKey(name: 'imdb_id')
  final String? imdbId;

  /// The original countries of production.
  @HiveField(8)
  @JsonKey(name: 'origin_country')
  final List<String>? originCountry;

  /// The original language of the movie.
  @HiveField(9)
  @JsonKey(name: 'original_language')
  final String? originalLanguage;

  /// The original title of the movie.
  @HiveField(10)
  @JsonKey(name: 'original_title')
  final String? originalTitle;

  /// A brief overview or synopsis of the movie.
  @HiveField(11)
  final String? overview;

  /// The popularity score of the movie.
  @HiveField(12)
  final double? popularity;

  /// The path to the movie's poster image.
  @HiveField(13)
  @JsonKey(name: 'poster_path')
  final String? posterPath;

  /// A list of companies that produced the movie.
  @HiveField(14)
  @JsonKey(name: 'production_companies')
  final List<ProductionCompany>? productionCompanies;

  /// A list of countries where the movie was produced.
  @HiveField(15)
  @JsonKey(name: 'production_countries')
  final List<ProductionCountry>? productionCountries;

  /// The release date of the movie.
  @HiveField(16)
  @JsonKey(name: 'release_date')
  final String? releaseDate;

  /// The total revenue generated by the movie.
  @HiveField(17)
  final int? revenue;

  /// The runtime of the movie in minutes.
  @HiveField(18)
  final int? runtime;

  /// A list of spoken languages in the movie.
  @HiveField(19)
  @JsonKey(name: 'spoken_languages')
  final List<SpokenLanguage>? spokenLanguages;

  /// The current status of the movie (e.g., "Released").
  @HiveField(20)
  final String? status;

  /// The tagline or catchphrase of the movie.
  @HiveField(21)
  final String? tagline;

  /// The title of the movie.
  @HiveField(22)
  final String? title;

  /// Indicates if the movie has a video (e.g., a trailer).
  @HiveField(23)
  final bool? video;

  /// The average vote score.
  @HiveField(24)
  @JsonKey(name: 'vote_average')
  final double? voteAverage;

  /// The total number of votes received.
  @HiveField(25)
  @JsonKey(name: 'vote_count')
  final int? voteCount;

  /// Creates a [MovieDetailsModel] instance.
  MovieDetailsModel({
    this.adult,
    this.backdropPath,
    this.belongsToCollection,
    this.budget,
    this.genres,
    this.homepage,
    this.id,
    this.imdbId,
    this.originCountry,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.productionCompanies,
    this.productionCountries,
    this.releaseDate,
    this.revenue,
    this.runtime,
    this.spokenLanguages,
    this.status,
    this.tagline,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });

  /// Creates a [MovieDetailsModel] from a JSON map.
  factory MovieDetailsModel.fromJson(Map<String, dynamic> json) =>
      _$MovieDetailsModelFromJson(json);

  /// Converts this [MovieDetailsModel] to a JSON map.
  Map<String, dynamic> toJson() => _$MovieDetailsModelToJson(this);
}

/// A data model for a movie genre.
@HiveType(typeId: 3)
@JsonSerializable()
class Genre extends HiveObject {
  /// The unique identifier for the genre.
  @HiveField(0)
  final int? id;

  /// The name of the genre.
  @HiveField(1)
  final String? name;

  /// Creates a [Genre] instance.
  Genre({this.id, this.name});

  /// Creates a [Genre] from a JSON map.
  factory Genre.fromJson(Map<String, dynamic> json) => _$GenreFromJson(json);

  /// Converts this [Genre] to a JSON map.
  Map<String, dynamic> toJson() => _$GenreToJson(this);
}

/// A data model for a production company.
@HiveType(typeId: 4)
@JsonSerializable()
class ProductionCompany extends HiveObject {
  /// The unique identifier for the company.
  @HiveField(0)
  final int? id;

  /// The path to the company's logo.
  @HiveField(1)
  @JsonKey(name: 'logo_path')
  final String? logoPath;

  /// The name of the company.
  @HiveField(2)
  final String? name;

  /// The country of origin for the company.
  @HiveField(3)
  @JsonKey(name: 'origin_country')
  final String? originCountry;

  /// Creates a [ProductionCompany] instance.
  ProductionCompany({this.id, this.logoPath, this.name, this.originCountry});

  /// Creates a [ProductionCompany] from a JSON map.
  factory ProductionCompany.fromJson(Map<String, dynamic> json) =>
      _$ProductionCompanyFromJson(json);

  /// Converts this [ProductionCompany] to a JSON map.
  Map<String, dynamic> toJson() => _$ProductionCompanyToJson(this);
}

/// A data model for a production country.
@HiveType(typeId: 5)
@JsonSerializable()
class ProductionCountry extends HiveObject {
  /// The ISO 3166-1 code for the country.
  @HiveField(0)
  @JsonKey(name: 'iso_3166_1')
  final String? iso3166_1;

  /// The name of the country.
  @HiveField(1)
  final String? name;

  /// Creates a [ProductionCountry] instance.
  ProductionCountry({this.iso3166_1, this.name});

  /// Creates a [ProductionCountry] from a JSON map.
  factory ProductionCountry.fromJson(Map<String, dynamic> json) =>
      _$ProductionCountryFromJson(json);

  /// Converts this [ProductionCountry] to a JSON map.
  Map<String, dynamic> toJson() => _$ProductionCountryToJson(this);
}

/// A data model for a spoken language.
@HiveType(typeId: 6)
@JsonSerializable()
class SpokenLanguage extends HiveObject {
  /// The English name of the language.
  @HiveField(0)
  @JsonKey(name: 'english_name')
  final String? englishName;

  /// The ISO 639-1 code for the language.
  @HiveField(1)
  @JsonKey(name: 'iso_639_1')
  final String? iso639_1;

  /// The native name of the language.
  @HiveField(2)
  final String? name;

  /// Creates a [SpokenLanguage] instance.
  SpokenLanguage({this.englishName, this.iso639_1, this.name});

  /// Creates a [SpokenLanguage] from a JSON map.
  factory SpokenLanguage.fromJson(Map<String, dynamic> json) =>
      _$SpokenLanguageFromJson(json);

  /// Converts this [SpokenLanguage] to a JSON map.
  Map<String, dynamic> toJson() => _$SpokenLanguageToJson(this);
}
